# Generated by Django 3.2 on 2021-04-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_blockeddays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedDays',
        ),
    ]
