# Generated by Django 3.2 on 2021-04-28 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_delete_blockeddays'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDays',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='blocked_day', serialize=False, to='listings.listing')),
                ('blocked_day', models.DateTimeField(verbose_name='Blocked day')),
            ],
        ),
    ]
