# Generated by Django 3.2 on 2021-04-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_blockeddays'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedDays',
            new_name='BlockedDay',
        ),
    ]
