# Generated by Django 3.2 on 2021-04-28 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_blockeddays'),
        ('units', '0002_rename_blockeddays_blockedday'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedday',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockedday',
            name='listing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.bookinginfo'),
        ),
    ]
