# Generated by Django 3.2 on 2021-04-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20210428_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedday',
            name='blocked_day',
            field=models.DateField(verbose_name='Blocked day'),
        ),
    ]
