# Generated by Django 3.2 on 2021-04-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_blockedday_blocked_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockedday',
            old_name='listing',
            new_name='booking_info',
        ),
    ]
