# Generated by Django 3.2 on 2021-04-29 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_blockeddays'),
        ('units', '0005_rename_listing_blockedday_booking_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedday',
            name='booking_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocked_day', to='listings.bookinginfo'),
        ),
    ]
